# Form implementation generated from reading ui file 'UI/Main.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1158, 608)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        Form.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.history_scrollArea = QtWidgets.QScrollArea(parent=Form)
        self.history_scrollArea.setWidgetResizable(True)
        self.history_scrollArea.setObjectName("history_scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 281, 268))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.history_scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout.addWidget(self.history_scrollArea, 3, 1, 1, 1)
        self.category_scrollArea = QtWidgets.QScrollArea(parent=Form)
        self.category_scrollArea.setWidgetResizable(True)
        self.category_scrollArea.setObjectName("category_scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 281, 268))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.category_scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.category_scrollArea, 2, 1, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(parent=Form)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.gridLayout.addWidget(self.tableWidget, 2, 0, 2, 1)
        self.buttons_horizontalLayout = QtWidgets.QHBoxLayout()
        self.buttons_horizontalLayout.setObjectName("buttons_horizontalLayout")
        self.gridLayout.addLayout(self.buttons_horizontalLayout, 1, 0, 1, 2)
        self.keyword_lineEdit = QtWidgets.QLineEdit(parent=Form)
        self.keyword_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.keyword_lineEdit.setObjectName("keyword_lineEdit")
        self.gridLayout.addWidget(self.keyword_lineEdit, 0, 0, 1, 1)
        self.select_none_pushButton = QtWidgets.QPushButton(parent=Form)
        self.select_none_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.select_none_pushButton.setObjectName("select_none_pushButton")
        self.gridLayout.addWidget(self.select_none_pushButton, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 3)
        self.gridLayout.setColumnStretch(1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.keyword_lineEdit, self.tableWidget)
        Form.setTabOrder(self.tableWidget, self.select_none_pushButton)
        Form.setTabOrder(self.select_none_pushButton, self.category_scrollArea)
        Form.setTabOrder(self.category_scrollArea, self.history_scrollArea)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "乐词网检索"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "English Term"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Chinese Term"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Category"))
        self.select_none_pushButton.setText(_translate("Form", "Select None"))
